export * from "./svg"
export { default as ProfileImage } from "./profile-icon.png"
export { default as HomeBottom } from "./home.svg"
export { default as BackIcon } from "./back.svg"
export { default as CallIcon } from "./call.svg"
export { default as RejectIcon } from "./reject.svg"
export { default as ContainerIcon } from "./container.svg"
export { default as EnterIcon } from "./Enter.svg"
export { default as DriverIcon } from "./Driver.svg"
export { default as UserIcon } from "./User.svg"
export { default as PinIcon } from "./Pin.svg"
export { default as RedPin } from "./RedPin.svg"
